services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - ./mongo/mongo.env
  express:
    build: ./express
    ports:
      - '3000:3000'
    env_file:
      - ./mongo/backend.env
      
  angular:
    build: ./angular
    ports:
      - '4201:4200'
volumes:
  data: