services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - ./mongo/mongo.env

  angular-docker:
    build: ./angular-docker
    ports:
      - '4201:4200'

  express:
    build: ./express
    ports:
      - '3000:3000'
    env_file:
      - ./mongo/backend.env
volumes:
  data: